#! /bin/csh -f
#
# Copyright 2003, 2004, 2005 PathScale, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement 
# or the like.  Any license provided herein, whether implied or 
# otherwise, applies only to this software file.  Patent licenses, if 
# any, provided herein do not apply to combinations of this program with 
# other software, or any other product whatsoever.  
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write the Free Software Foundation, Inc., 59
# Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
#       invoke cygnus configure to set up this directory as an
#       ia32-host x86_64-target build area
#

#setenv CFLAGS " -g -O2 -m32 -mno-sse2"
setenv CFLAGS " -g -O0 -m32"

#set bk_root=`bk root`
#${bk_root}/open64/process-defs csh - | source /dev/stdin

set     SRC_DIR         = ../cygnus
set	INSTALL_DIR	= /usr/x8664-linux #${OPEN64_INSTALL_PREFIX}
set     CONFIGURE       = ${SRC_DIR}/configure
set     HOST            = i686-open64-linux
set     BUILD           = i686-open64-linux
set     TARG            = x86_64-open64-linux #${OPEN64_TARGET}

${CONFIGURE}                   \
    --srcdir=${SRC_DIR}        \
    --prefix=${INSTALL_DIR}    \
    --host=${HOST}             \
    --target=${TARG}
