OPENUH_NAME_PREFIX=uh

OPENUH_MAJOR_VERSION=3
OPENUH_MINOR_VERSION=0
OPENUH_PATCH_LEVEL=38

OPENUH_FULL_VERSION=${OPENUH_MAJOR_VERSION}.${OPENUH_MINOR_VERSION}.${OPENUH_PATCH_LEVEL}

OPEN64_NAME_PREFIX=open

OPEN64_MAJOR_VERSION=5
OPEN64_MINOR_VERSION=0
OPEN64_PATCH_LEVEL=

OPEN64_FULL_VERSION=${OPEN64_MAJOR_VERSION}.${OPEN64_MINOR_VERSION}

OPEN64_GCC_VERSION=3.3.1
OPEN64_GCC40_VERSION=4.0.2
OPEN64_GCC42_VERSION=4.2.0
OPEN64_ROOT_PREFIX=
OPEN64_INSTALL_PREFIX=/usr
OPEN64_INCLUDE_DIR=
