#! /bin/csh -f
#
#       invoke cygnus configure to set up this directory as an
#       ia32-host ia64-target build area
#

#CFLAGS=" -g -I$TARG_ISA_INCLUDE -I$SGIDEFS_INCLUDE
#export CFLAGS
setenv CFLAGS " -g -O0 -fno-exceptions -ffloat-store -D__MIPS_AND_IA64_ELF_H"

set     SRC_DIR         = ../cygnus
set	INSTALL_DIR	= /usr/ia64-sgi-linux
set     CONFIGURE       = ${SRC_DIR}/configure
set     HOST            = ia64-linux-gnu
set     BUILD           = ia64-linux-gnu
set     TARG            = ia64-linux-gnu

${CONFIGURE}                   \
    --srcdir=${SRC_DIR}        \
    --prefix=${INSTALL_DIR}    \
    --host=${HOST}             \
    --target=${TARG}
